### ISSUE TITLE
More details in README

### ISSUE THREAD

**Issue by hijarian** [milgner/k290-fnkeyctl#11]
Three issues.

1. You are amazing for solving such a precise, small-scale pain point and publishing it. Seriously. GitHub doesn't have place to put praises into, so I am writing it as an issue.
2. Sorry for not being a diehard coder who always looks into the sources of the solutions presented for him, but it would be nice to clean up the contradiction in the README: you mention that clang is required for compiling your binary, but `clang` invocation is commented out in `build.sh`, and `g++` (from a totally separate package) is used instead. Please, either comment the `g++` invocation instead or mention that one actually needs `g++` in the README.
3. It would be just great to mention that after the building and installing unplugging and plugging the keyboard back will probably help if *nothing at all* is happening. It was the issue for me, as everything just silently completed, all binaries were put into proper placed, even `udev` was completely restarted and nevertheless the behavior of f-keys was not changed. Only physical unplugging helped.

Also, I noticed the following more step-by-step instructions (for Debian, supposedly) in the Web, maybe they'll be helpful to write in README, too:

```shell
$ sudo apt-get install g++ libusb-1.0-0-dev
$ git clone https://github.com/milgner/k290-fnkeyctl
$ cd k290-fnkeyctl
$ g++ -std=c++11  k290_fnkeyctl.cpp -lusb-1.0 -o k290_fnkeyctl
$ sudo install -o root -g root -m 0755 ./k290_fnkeyctl /usr/local/sbin
$ sudo install -o root -g root -m 0644 ./99-k290-config.rules /etc/udev/rules.d
$ sudo udevadm control --reload-rules
$ sudo udevadm trigger --subsystem-match=input
```

Courtesy of: http://blog.tataranovich.com/2014/07/logitech-comfort-keyboard-k290.html

**Comment by milgner** [comment]
Thank you, both for the praise and the feedback! Also for linking the article - I added the `udevadm` commands to the readme for clarification along with a note to install `libusb-1.0-0-dev` on Debian-based systems.
