### ISSUE TITLE
Doesn't work on Fedora

### ISSUE THREAD

**Issue by voyagerok** [milgner/k290-fnkeyctl#18]
Installed as package from copr on Fedora 23. Here is log http://pastebin.com/k6KPEAer

**Comment by voyagerok** [comment]
As I understood from the error code, k290 keyboard was not found. Here is lsusb http://pastebin.com/ayiYYgr3

**Comment by voyagerok** [comment]
Changing /usr/local/sbin to /usr/sbin in SPEC file solved the problem.

**Comment by mariuszs** [comment]
Are you sure? because systemd rule uses /usr/local/sbin

**Comment by mariuszs** [comment]
OK, you are right, because version 1.1 has different rule inside :(

**Comment by mariuszs** [comment]
Ok, fixed https://copr-be.cloud.fedoraproject.org/results/mariuszs/k290-fnkeyctl/fedora-23-x86_64/00175772-k290-fnkeyctl/k290-fnkeyctl-1.1-2.fc23.x86_64.rpm

`dnf update` should be enough

**Comment by voyagerok** [comment]
Thanks!

**Comment by mariuszs** [comment]
@milgner please close this issue
