### ISSUE TITLE
Error on install.sh

### ISSUE THREAD

**Issue by qtheuret** [milgner/k290-fnkeyctl#21]
When I run sudo ./install.sh on Ubuntu 16.04, I get this error:

```
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
k290_fnkeyctl.cpp:6:31: fatal error: libusb-1.0/libusb.h: Aucun fichier ou dossier de ce type
compilation terminated.
Could not build
install: impossible d'évaluer 'k290_fnkeyctl': Aucun fichier ou dossier de ce type
```

I think this could be fix by rename the k290-fnkeyctl.sh to k290_fnkeyctl or change the path to the good script on install.sh

**Comment by milgner** [comment]
Thank you for the report! It looks like it cannot find libusb. Is the corresponding `-dev` package installed? I re-checked and 1.0 still should be the latest version. But I could not find any package for 16.04 in the [web package search](http://packages.ubuntu.com/search?keywords=libusb). Could you check whether `libusb-1.0-0-dev` is available and installed on your system?

**Comment by qtheuret** [comment]
Ok, thanks. `libusb-1.0-0-dev` package was not installed on my system. After installation of this package, the script works fine.
